name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # كل يوم
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: generate snake svg
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: alaaeliwa
          outputs: |
            dist/snake-alaa.svg
      - name: Push snake svg
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
